### ISSUE TITLE
tab_color call prints garbage to terminal

### ISSUE THREAD

**Issue by jjoltes** [dotphiles/dotzsh#11]
I've just forked and setup this project - which looks awesome. but my prompt is printing `]6;1;bg;*;default%` on the line above the cursor. 

my locale and unicode seem to be correct. 
en_US.UTF-8

It seems to be line 145 of modules/terminal/init.zsh that is causing the issue
`tab_reset() { echo -n -e "\033]6;1;bg;*;default\a" }`

What do I have configured wrong?

**Comment by benohara** [comment]
Are you using iterm2?  Looks like it only works on iterm2, but gets run in any terminal....I'll have a look into it.

**Comment by benohara** [comment]
try the 'develop' branch...I only use iterm2 and tested it under apple terminal, both looked ok but I've made this only trigger if its iterm2 (as far as I know those escape codes only work for iterm anyways)

**Comment by jjoltes** [comment]
That fixed it! Thank you! BTW I run gnome-terminal on centos and xterm on ubuntu so I'll probably make a good guinea pig for you. awesome project - awesome work, thanks!

**Comment by benohara** [comment]
Nice one, yeah, raise any issues you find, i'd image it'll just be stuff around the terminal that might not work...everything else should be platform independent....i uses it on loads of centos boxes (5,6,7)
